# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PepBandWebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=25)),
                ('cell', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=15)),
            ],
        ),
    ]
