# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PepBandWebsite', '0003_auto_20170701_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='public',
        ),
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('Pu', 'Public'), ('Pr', 'Private')], default='Pr', max_length=2),
        ),
    ]
