# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PepBandWebsite', '0004_auto_20170701_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eboard',
            name='position',
            field=models.CharField(choices=[('T', 'Treasurer'), ('C', 'Conductor'), ('VP', 'Vice President'), ('S', 'Secretary'), ('P', 'President')], max_length=2),
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(choices=[('F', 'Flutes'), ('Cl', 'Clarinets'), ('AS', 'Alto Saxophones'), ('Tpt', 'Trumpets'), ('M', 'Mellophones'), ('TS', 'Tenor Saxophones'), ('Trb', 'Trombones'), ('Tub', 'Tubas'), ('P', 'Percussion')], max_length=2),
        ),
    ]
