# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PepBandWebsite', '0005_auto_20170701_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(choices=[('F', 'Flutes'), ('Cl', 'Clarinets'), ('AS', 'Alto Saxophones'), ('Tpt', 'Trumpets'), ('M', 'Mellophones'), ('TS', 'Tenor Saxophones'), ('Trb', 'Trombones'), ('Tub', 'Tubas'), ('P', 'Percussion')], max_length=3),
        ),
    ]
