# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PepBandWebsite', '0007_auto_20170702_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eboard',
            name='position',
            field=models.CharField(choices=[('Treasurer', 'Treasurer'), ('Conductor', 'Conductor'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('President', 'President')], max_length=15),
        ),
    ]
