# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PepBandWebsite', '0008_auto_20170702_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(choices=[('Flutes', 'Flutes'), ('Clarinets', 'Clarinets'), ('Saxophones', 'Alto Saxophones'), ('Trumpets', 'Trumpets'), ('Mellophones', 'Mellophones'), ('Tenor Saxophones', 'Tenor Saxophones'), ('Trombones', 'Trombones'), ('Tubas', 'Tubas'), ('Percussion', 'Percussion')], max_length=3),
        ),
    ]
