# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PepBandWebsite', '0011_auto_20170702_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Pr', max_length=2),
        ),
    ]
