# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PepBandWebsite', '0012_auto_20170702_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video',
            field=models.CharField(default='', max_length=100),
        ),
    ]
