# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PepBandWebsite', '0014_auto_20170708_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='video',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
