# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PepBandWebsite', '0017_song_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='notes',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='eboard',
            name='cell',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='cell',
            field=models.CharField(max_length=10),
        ),
    ]
